In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Creating a copy
arr_copy = arr.copy()

# Modifying the copy
arr_copy[0] = 10

print("origanal arr= ",arr)        
print("copy array = ",arr_copy)   


origanal arr=  [1 2 3 4 5]
copy array =  [10  2  3  4  5]


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Creating a view
arr_view = arr.view()

# Modifying the view
arr_view[0] = 10

print(arr)        # Output: [10  2  3  4  5]
print(arr_view)   # Output: [10  2  3  4  5]


[10  2  3  4  5]
[10  2  3  4  5]


In [7]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])

for i in np.nditer(arr):
    print(i)
##The np.nditer() function allows you to traverse the array in various orders, control iteration behavior, and perform operations while iterating through the elements. 


1
2
3
4
5
6


In [9]:
arr=np.arange(0,6)
arr

array([0, 1, 2, 3, 4, 5])

In [10]:
for i in np.nditer(arr):
    print(i)

0
1
2
3
4
5


In [11]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

Array = np.concatenate((arr1, arr2))
print(Array) 

[1 2 3 4 5 6]


In [14]:
Array = np.concatenate((arr1, arr2)).reshape(3,2)
print(Array)

[[1 2]
 [3 4]
 [5 6]]


In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

# Splitting the array
split_arr = np.array_split(arr, 8)
print(split_arr)


[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int32), array([], dtype=int32)]


In [18]:
import numpy as np

arr = np.array([3, 2, 1, 5, 4])

# Searching for an element
print(np.where(arr == 3))  



(array([0], dtype=int64),)


In [19]:
# Sorting the array
sorted_arr = np.sort(arr)
print(sorted_arr)  



[1 2 3 4 5]


In [20]:
# Filtering elements
filtered_arr = arr[arr > 2]
print(filtered_arr)  


[3 5 4]
