What is NumPy

NumPy is a Python library used for working with arrays.It also has functions for working in domain of linear algebra, fourier transform, and matrices. NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.NumPy stands for Numerical Python.

NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python.

What is an array

An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

Why Use NumPy?

In Python we have lists that serve the purpose of arrays, but they are slow to process.NumPy aims to provide an array object that is up to 50x faster than traditional Python lists. The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy. Arrays are very frequently used in data science, where speed and resources are very important.

Data Science: is a branch of computer science where we study how to store, use and analyze data for deriving information from it.

Why is NumPy Faster Than Lists?

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently. This behavior is called locality of reference in computer science. This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.


Where is the NumPy Codebase?

The source code for NumPy is located at this github repository https://github.com/numpy/numpy

Installation of NumPy

If you have Python and PIP already installed on a system, then installation of NumPy is very easy. Install it using this command: C:\Users\Your 

Name>pip install numpy

If this command fails, then use a python distribution that already has NumPy installed like, Anaconda, Spyder etc.

In [1]:
import numpy as np

In [2]:
# Once NumPy is installed, import it in your applications by adding the import keyword:
import numpy
#Now NumPy is imported and ready to use.

## import the library
import numpy as np

In [ ]:
import numpy as np

print(np.__version__)

In [4]:
lst=[1,2,3,4]
lst

[1, 2, 3, 4]

In [5]:
arr=np.array(lst)
print(arr)

[1 2 3 4]


In [6]:
type(arr)

numpy.ndarray

In [7]:
arr.shape

(4,)

In [8]:
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]

arr1=np.array([lst1,lst2,lst3])

In [9]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [10]:
arr1.shape

(3, 5)

In [11]:
arr

array([1, 2, 3, 4])

In [12]:
#indexing
arr[3]

4

In [13]:
arr[3]=5

In [14]:
arr[-1]

5

In [15]:
arr

array([1, 2, 3, 5])

In [16]:
arr[:-1]

array([1, 2, 3])

In [17]:
arr[::-3]

array([5, 1])

In [18]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [19]:
arr1[:,3:].shape

(3, 2)

In [20]:
arr1[:,1]

array([2, 3, 4])

In [21]:
arr1[1:,1:3]

array([[3, 4],
       [4, 5]])

In [22]:
arr1[1:,3:]

array([[5, 6],
       [6, 7]])

In [23]:
##EDA
arr

array([1, 2, 3, 5])

In [24]:
arr[arr<2]

array([1])

In [25]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [26]:
arr1.reshape(5,3)


array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [27]:
##mechanism to create an array
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [28]:
np.arange(1,20,2).reshape(2,5,1)

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9]],

       [[11],
        [13],
        [15],
        [17],
        [19]]])

In [29]:
arr *arr

array([ 1,  4,  9, 25])

In [30]:
arr1 * arr1

array([[ 1,  4,  9, 16, 25],
       [ 4,  9, 16, 25, 36],
       [ 9, 16, 25, 36, 49]])

In [31]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
np.random.randint(10,50,4).reshape(2,2)

array([[33, 21],
       [40, 33]])

In [34]:
np.random.randn(5,6)

array([[-0.35353272, -0.47291599,  0.87995165,  0.31998765,  0.34736067,
        -1.15575853],
       [-0.64421224, -0.56586132, -0.88084838,  0.18640199,  1.27361712,
        -0.34921042],
       [-0.53510762, -1.01462503,  0.88501366, -0.18897801,  1.65856001,
        -1.97471021],
       [ 1.19270622,  0.14692287, -0.35766348,  1.1308405 , -0.48550671,
         0.0362393 ],
       [-0.67142495, -1.10164113, -0.70470609, -0.4150266 , -0.61952097,
         0.04617605]])

In [35]:
np.random.random_sample((4,7))

array([[0.92826772, 0.92975406, 0.65692944, 0.49663033, 0.16461832,
        0.1316079 , 0.1889009 ],
       [0.47154012, 0.9658191 , 0.87821776, 0.75931202, 0.89075305,
        0.29183393, 0.4959174 ],
       [0.01360134, 0.15217037, 0.54921681, 0.19500631, 0.58006988,
        0.65804876, 0.41128197],
       [0.75388128, 0.33552313, 0.2677101 , 0.75377408, 0.74984041,
        0.02712435, 0.38434691]])