In [1]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable


In [13]:
import pandas as pd
import numpy as np
np.arange(0,20) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [15]:
pd.DataFrame(data=np.arange(0,20).reshape(5,4),
             index=["Row1","Row2","Row3","Row4","Row5"],
             columns=["Column1","Column2","Column3","Column4"])

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [17]:
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=["Row1","Row2","Row3","Row4","Row5"],columns=["Column1","Column2","Column3","Column4"])

In [18]:
print(df)

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19


In [19]:
df.head(2)

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7

In [21]:
df.tail(1)

Column1  Column2  Column3  Column4
Row5       16       17       18       19

In [9]:
type(df)

pandas.core.frame.DataFrame

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  5 non-null      int32
 1   Column2  5 non-null      int32
 2   Column3  5 non-null      int32
 3   Column4  5 non-null      int32
dtypes: int32(4)
memory usage: 120.0+ bytes


In [11]:
df.describe()

Column1    Column2    Column3    Column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [12]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [22]:
df[['Column1','Column2']]#by using columnname


Column1  Column2
Row1        0        1
Row2        4        5
Row3        8        9
Row4       12       13
Row5       16       17

In [24]:
df['Column1']
type(df['Column1'])

pandas.core.series.Series

In [15]:
#by using a row index name or  that is called loc parameter
import pandas as pd

# Assuming df is your DataFrame
row = df.loc['Row1'] 
print(row)

Column1    0
Column2    1
Column3    2
Column4    3
Name: Row1, dtype: int32


In [16]:
df.loc[['Row1','Row2']]

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7

In [26]:
df.loc[['Row1','Row5']]

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row5       16       17       18       19

In [18]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [19]:
df.iloc[2:4,0:2] #by using iloc

Column1  Column2
Row3        8        9
Row4       12       13

In [20]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [21]:
df.iloc[1:4,1:3]

Column2  Column3
Row2        5        6
Row3        9       10
Row4       13       14

In [27]:
df.iloc[1:4:2,1:3]

Column2  Column3
Row2        5        6
Row4       13       14

In [28]:
df.iloc[1:,2:]

Column3  Column4
Row2        6        7
Row3       10       11
Row4       14       15
Row5       18       19

In [24]:
#if i want to convert the data frame into arrays
df.iloc[1:4,1:3].values

array([[ 5,  6],
       [ 9, 10],
       [13, 14]])

In [25]:
##basic operations in df
df.isnull()

Column1  Column2  Column3  Column4
Row1    False    False    False    False
Row2    False    False    False    False
Row3    False    False    False    False
Row4    False    False    False    False
Row5    False    False    False    False

In [26]:
df.isnull().sum()==0

Column1    True
Column2    True
Column3    True
Column4    True
dtype: bool

In [27]:
df['Column1'].value_counts()

0     1
4     1
8     1
12    1
16    1
Name: Column1, dtype: int64

In [28]:
df

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19